spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf-8
    username: root
    password: 123456
#    #配置监控统计拦截的filters，去掉监控界面sql将无法统计,'wall'用于防火墙
#    filters: stat,wall,log4j
#    max-active: :
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

